dependecies:
- any: ['package.json', 'package-lock.json']

modules:
- any: ['modules/**/*']

commands:
- any: ['commands/**/*']

events:
- any: ['modules/events/*']

configuration:
- any: ['config.yaml']

documentation:
- any: ['CODE_OF_CONDUCT.md', 'LICENSE', 'README.md', 'SCURITY.md']

ci:
- any: ['.github/*', '.gitignore', '.gitattributes']