############################################################################
##      _          _   _        _   _      ___  ___ _____                 ##
##     /_\  ___ __| |_| |_  ___| |_(_)__  | _ )/ _ \_   _|                ##
##    / _ \/ -_|_-<  _| ' \/ -_)  _| / _| | _ \ (_) || |                  ##
##   /_/_\_\___/__/\__|_||_\___|\__|_\__| |___/\___/ |_|__  ___  ___      ##
##   | _ )_  _    /_\  ___ __| |_| |_  ___| |_(_)__   / _ \| _ \/ __|     ##
##   | _ \ || |  / _ \/ -_|_-<  _| ' \/ -_)  _| / _| | (_) |   / (_ |_    ##
##   |___/\_, | /_/ \_\___/__/\__|_||_\___|\__|_\__|  \___/|_|_\\___(_)   ##
##        |__/                                                            ##
############################################################################

############################################
#                                          #
#   Need Help?                             #
#                                          #
############################################
# Check out the documetation at            #
# https://docs.aesthetic-bot.com           #
############################################

############################################
#                                          #
#   Bot Config                             #
#                                          #
############################################
# Bot Token in an .env file for safety...  #
# Learn more in README.md                  #
############################################
locale: en-gb

############################################
# Where is the prefix setting?             #
# With Discord.js v13 we have decided to   #
# only support SLASH (/) commands.         #
############################################

embed:
  color:
    default: WHITE
    warn: ORANGE
    error: RED
  footer:
    text: Aesthetic BOT
    icon: https://i.imgur.com/PQY5oE6.png

# GOING TO IMPLEMENT WITH /settings COMMAND
#Moderation:
#  AutoMod:
#    - [2, 'warn', 'tempmute', '30m']
#    - [3, 'warn', 'mute']
#    - [5, 'warn', 'kick']
#    - [2, 'kick', 'tempban', '7d']
#    - [2, 'tempban', 'ban']
#    # [ammount, 'trigger', 'action', 'length']
#  Mute:
#    Role: 'Muted'
#    LowerRolesOnly: true
#  Warn:
#    CanWarnRolesAbove:
#      Bot: true
#      User: false
#      UserSame: false

status:
  interval: 60000
  ordered: false
  list: [
    { status: 'online', type: 'LISTENING', name: 'Kanye West'},
    { status: 'online', type: 'LISTENING', name: 'new commands'},
    { status: 'online', type: 'LISTENING', name: 'my master'},
    { status: 'online', type: 'LISTENING', name: 'mods'},
    { status: 'online', type: 'WATCHING', name: 'members'},
    { status: 'online', type: 'WATCHING', name: 'people burn'},
  ]

currency:
  symbols: 
    - EUR
    - USD
    - CHF
    - GBP
    - CAD
    - JPY
    - CNY
    - INR
  amount: 
    min: 0.01
    max: 1.00E+12 #Represents 1 000 000 000 000

meme:
  defaultSubreddit: memes
  validSubreddits:
    - memes
    - meme
    - dankmemes
    - goodanimememes
    - animememes
    - christianmemes
    - memeeconomy
    - minecraftmemes
    - nukedmemes
    - surrealmemes
    - jojomemes

reddit:
  defaultType: random
  bannedSubreddits:
    enabled: false
    list: # Note: NSFW subredits are automaticly filtered here, they can only be shown in NSFW channels.
      - something

logs:
  channel: logs
  enabled:
    channelCreate: true
    channelDelete: true
    channelPinsUpdate: true
    emojiCreate: true
    emojiDelete: true
    emojiUpdate: true
    inviteCreate: true
    inviteDelete: true
    roleCreate: true
    roleDelete: true
    roleUpdate: true

############################################
#                                          #
#   Warning! The eval command is a very    #
#   risky command, it should only be on    #
#   if you know what you are doing!        #
#                                          #
############################################
eval:
  enabled: false
# The owner ID can be changed at the beginning of this file
# This command allows to run javascript straight from a text channel!

############################################
#                                          #
#   Console Customisation                  #
#                                          #
############################################
consoleStyle:
  prefix:
    info: INFO >
    warn: WARN >
    error: ERROR >
    mod: MOD >
    log: LOG >
  color:
    # In modules/utils.js

# [!] Not implemented yet
consoleOutput:
  log:
    messages: false
    voiceChannels: false
    commandsRan: false
    invalidCommands: false
    otherActions: true